### ISSUE TITLE
BSDDB3 is not installable

### ISSUE THREAD

**Issue by OzarkShepherd** [gramps-project/flatpak#3]
Oracle requires an account to download BSDDB for free, which makes it difficult to put into the flatpak.  Furthermore, when I downloaded old versions of BSDDB3 from oracle, the unix directory was empty in the db-6.1.23.tar.gz and db-6.1.23.NC.tar.gz as of 12 Nov 2020.

**Comment by Nick-Hall** [comment]
The BSDDB backend will be removed in the next major release.  We will only be keeping the dependency to allow a database upgrade.

I am not particularly concerned about this.  I don't see many people installing a Flatpak on a machine already Gramps installed.

**Comment by OzarkShepherd** [comment]
If you install a flatpak without removing a previous version, you might get two Gramps launchers in the menu.  The Gramps flatpak with its home directory access will find the current Gramps file and settings and use them.  

The problem that could happen is if the previous version has an add-on with optional dependencies not available in the flatpak, then errors will pop up and the features will be disabled when the Gramps flatpak starts.  Or in my case with the other goocanvas 2 issue, when I opened the prior Gramps 5.1.2 installed from source, the Gramps flatpak couldn't find the goocanvas 2 dependency in the flatpak for GraphView.  So it gave me some pop up errors about not being able to use some features.

So from what I saw, it is just an annoyance and nothing catastrophic that I am aware of.  Actually, I just realized that I still have 5.1.2 installed from source on my computer and it still launches from the command line.  The Gramps icon and launcher launch the flatpak on my system, I must have deleted the prior icon and launcher from my system already since I couldn't find those in the normal places.  Flatpak launchers and icons install into a different directory than the Gramps installations that are from source or repos.

**Comment by a-andre** [comment]
In case you are still interested in bsddb support
```
  - name: db
    subdir: dist
    builddir: true
    config-opts:
      - "--enable-compat185"
      - "--enable-shared"
      - "--enable-cxx"
      - "--enable-dbm"
      - "--enable-stl"
    sources:
      - type: archive
        url: https://download.oracle.com/berkeley-db/db-5.3.28.tar.gz
        sha256: e0a992d740709892e81f9d93f06daf305cf73fb81b545afe72478043172c3628
      - type: patch
        path: atomic.patch

  - name: python3-bsddb
    buildsystem: simple
    build-options:
      env:
        BERKELEYDB_DIR: /app
    build-commands:
      - python3 setup.py build
      - python3 setup.py install --prefix=/app
    sources:
      - type: archive
        url: https://files.pythonhosted.org/packages/source/b/bsddb3/bsddb3-6.2.7.tar.gz
        sha256: b0f7fa63eb240cd5815809c9d1d7df9f7cc8d6fa9619d0edbe9c794afc02dc9f
```

Content of `atomic.patch`:
```patch
--- a/src/dbinc/atomic.h	2013-03-12 14:07:22.000000000 -0400
+++ b/src/dbinc/atomic.h	2013-03-12 14:06:35.000000000 -0400
@@ -144,7 +144,7 @@
 #define	atomic_inc(env, p)	__atomic_inc(p)
 #define	atomic_dec(env, p)	__atomic_dec(p)
 #define	atomic_compare_exchange(env, p, o, n)	\
-	__atomic_compare_exchange((p), (o), (n))
+	__atomic_compare_exchange_db((p), (o), (n))
 static inline int __atomic_inc(db_atomic_t *p)
 {
 	int	temp;
@@ -176,7 +176,7 @@
  * http://gcc.gnu.org/onlinedocs/gcc-4.1.0/gcc/Atomic-Builtins.html
  * which configure could be changed to use.
  */
-static inline int __atomic_compare_exchange(
+static inline int __atomic_compare_exchange_db(
 	db_atomic_t *p, atomic_value_t oldval, atomic_value_t newval)
 {
 	atomic_value_t was;
```

Inspired by
* https://github.com/archlinux/svntogit-packages/tree/packages/db/trunk
* https://github.com/archlinux/svntogit-community/tree/packages/python-bsddb/trunk
